# Guest Speakers {#guests}
We host a range of events and talks by guest speakers that employers can deliver or engage with.




## Guest lectures from employers {#guestlectures}

The Department of Computer Science welcomes external speakers and hosts a number of guest lectures from a wide range of collaborators in industry and academia. There are several ways the department can host guest lectures

* Scheduled lectures for [COMP101](https://studentnet.cs.manchester.ac.uk/ugt/COMP10120/syllabus/), a first year course with 400+ enrolled students. During 2021, these talks take place on Mondays from midday to 12.50pm on zoom
* School research seminars , see [examples of past seminars](https://www.cs.manchester.ac.uk/connect/events/past-events/)
* Technical talks arranged as part of a scheduled course, speak to the [course leader for the relevant course](https://www.cs.manchester.ac.uk/about/people/). These tend to be more advanced courses aimed at students later in their degrees or as part of postgraduate study.
* One-off talks arranged *ad hoc* that are not part of scheduled series of lectures
* Seminars and talks from speakers arranged and booked by students, for example [unicsmcr.com](https://unicsmcr.com/), The University of Manchester Computer Science society

### Examples of COMP101 lectures

Some example guest lectures for COMP101 are shown below to give a flavour of the kind of talks that are appropriate

* Hacking the Hacks, delivered by NCC Group
* Debunking the myths associated with User Experience, delivered by American Express
* The Business of Intellectual Property, delivered by Imagination Technology)
* How to Break a Hacker's Mind, Web Application Vulnerabilities Exposed, delivered by Morgan Stanley
* 100 billion ARM chips, delivered by ARM
* Software at Airbus
* Computing in the Community, delivered by CodeClub & Manchester Girl Geeks
* How to be a brilliant software engineer, delivered by Apadmi


### Interested in speaking?
For COMP101, we are always looking for good speakers who can engage large groups of students on interesting topics that they care about and relate to Computer Science. For COMP101, there are a limited number of guest lecture slots (around 20) which run through term-time starting in November and finishing in early June. Its important that speakers

* Give much more than a sales pitch for an organisation, by providing insight into a technical subject
* Talk about content that relates to the (very broad) syllabus of COMP101
* Engage, interact, educate and entertain. Students vote with their feet (by not turning up) if they think a lecture won't be interesting
* If you would like to propose a guest lecture for COMP101, please contact Duncan Hull. For all other external seminars and events, see the links above.

Since lockdown, lectures have been online, which has allowed for more interaction, typically via the chat dialogue. We can monitor and moderate the chat, feeding questions to the speaker when it's appropriate.


## Scheduled guest lectures 
guest lectures


## industrial mentoring 

Our industrial mentoring program 


## Bespoke and pop-up events



## Junior and senior {#junior}

We welcome talks from both junior and senior guests alike. Junior speakers have the advantage of being closer in age to the audience and it gives early careers gradautes a good opportunity and experience to developer their public speaking skills. 

Senior speakers have the advantage of extra insights and experience. An example of a more junior talk is shown below. 

```{r, eval=knitr::is_html_output(excludes = "epub"), results='asis', echo=FALSE}
cat('<iframe src="https://www.linkedin.com/embed/feed/update/urn:li:share:7305164652924076034" height="984" width="504" frameborder="0" allowfullscreen="" title="Embedded post"></iframe>')
```
